### ISSUE TITLE
endless for loop problem!!

### ISSUE THREAD

**Issue by dangdkhanh** [SunsetQuest/BigFloat#1]
Hi,
please check this code:
Bigfloat num1("200000000000000000000042423");
Bigfloat num2("2");
num1/=num2;

Thank you!

**Comment by SunsetQuest** [comment]
Hi! Thank you for your message. I ran the code in release and debug but did not get any endless loop issue.   Let me know if I am missing something.

```
        BigFloat number1 = BigFloat.Parse("200000000000000000000042423");
        BigFloat number2 = BigFloat.Parse("2");
        number1 /= number2;
        Console.WriteLine($"Result: {number1}");
```
And I get the result:  `Result: 1e+26`

Note: This is correct as the decimal input "2" has only a few bits of precision, so only a few bits of precision (or 1 decimal number) is returned.

**Comment by dangdkhanh** [comment]
Hi,
Thanks for the reply. something strange is happening with my code. 
I will try to investigate further in the next days.
